// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://burxedzkpugyavsqkzaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1cnhlZHprcHVneWF2c3FremFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNjQ0NzcsImV4cCI6MjA2OTY0MDQ3N30.p9o0yKp8_r4YSNMK7AOccrLGKYllYUemcrlWlIQob_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});