// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://homiaukwgrccinqfunna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvbWlhdWt3Z3JjY2lucWZ1bm5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NjM0NDAsImV4cCI6MjA2MDIzOTQ0MH0.i9Q8fW_F5kN9NLhosCsgBrdYU66P_l2_AnRt2t1vkrA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});